baseURL = 'https://cullenmacdonald.com/'
languageCode = 'en-us'
title = 'Cullen MacDonald'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  author = 'Cullen MacDonald'
  description = 'A year of small weekly prompts to help your team notice what’s working, shape how you work, and adapt together as things change.'
  email = 'hello@cullenmacdonald.com'
  linkedin = 'https://www.linkedin.com/in/cullen-macdonald-2a097959'
  github = 'https://github.com/cullenbmacdonald'
  substack = 'https://cullenm.substack.com'

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
